### ISSUE TITLE
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.

### ISSUE THREAD

**Issue by pirat8** [be9/acl9#105]
I think this comes from:
controller_extensions/generators.rb:          controller_class.send(:before_filter, options, &self.to_proc)
controller_extensions/generators.rb:          controller_class.send(:before_filter, @method_name, options)

Would be nice when the warning could disappear because rails5.1.beta1 is released.

**Comment by smathy** [comment]
Thanks, although I don't think our tests pass on even 5.0 let alone 5.1.  Will add this to my list of things to do when I get enough time or money :)

**Comment by smathy** [comment]
Fixed in d4a5ee0 - sorry for the delay there.  I pushed version 3.0.0 of the gem, so you can get this with:

```ruby
gem 'acl9', '~> 3.0'
```

**Comment by porschberg** [comment]
Great, thank you!

**Comment by smathy** [comment]
Sorry it took soooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo long, and thanks for creating the issue.
