### ISSUE TITLE
Project maintained?

### ISSUE THREAD

**Issue by threadhead** [be9/acl9#107]
Sorry to have to ask, but is this actively maintained?

We are considering using acl9, but I see the last major version release was nearly 3 years ago with no followup bug fixes, and a couple of still open issues.

**Comment by smathy** [comment]
Haven't had a release mostly because it's very stable.  Rails 5.x compatibility is the only (significant) issue, I'll work on it now and push out a new release.

**Comment by smathy** [comment]
Ok, I just pushed Rails 5 compatibility in version 3:

```ruby
gem 'acl9', '~> 3.0'
```

**Comment by threadhead** [comment]
Thanks!

**Comment by smathy** [comment]
Thanks for creating the issue.  This has been a long time coming, and I needed the poke.
