### ISSUE TITLE
Upgrading from 0.12.1 to 3.1.0: acts_as_authorisation_subject overriding users association

### ISSUE THREAD

**Issue by ecoologic** [be9/acl9#110]
Hi there,

We have a Rails 5.0.7 (Ruby v2.2.10) application using ACL9 v0.12.1.  Precisely the Gemfile is pointing to [this fork, master branch](https://github.com/zagraves/acl9).

I am trying to update it to your latest v3.1.0 and I'm having a few issues.  In my understanding ACL9 is _now_ defining a `users` association on our `Organisation` model through `acts_as_authorization_subject`, which I infer from this piece of doc [here](https://github.com/be9/acl9/wiki/Role-Subsystem#subject-model-1).

Using the old gem the active record association was called, but using the latest gem [this snippet](https://github.com/be9/acl9/blob/master/lib/acl9/model_extensions.rb#L86) is overriding the AR association.

Maybe I could understand better how to fix our problem if this TODO part was written:

> TODO - also add the object.users and object.users :manager interface.

But any help is appreciated.

## Context

This is what we have:

    class User < ActiveRecord::Base
      acts_as_authorization_subject association_name: :roles, join_table_name: :roles_users
      belongs_to :organisation
      # [...]
    end
    
    class Organisation < ActiveRecord::Base
      acts_as_authorization_object
      has_many :users # Gets overwritten and now returns []
      # [...]
    end

Thank you very much.

**Comment by smathy** [comment]
Hey there, sorry for the delay...

That association has always been there ([here's the code for it in 0.12.1](https://github.com/be9/acl9/blob/0.12.1/lib/acl9/model_extensions.rb#L93)), but yeah, the association in 3.x is now called `assoc_users` and as you pointed out, a new method has been written called `users` which will be masking your association.

Seeing as you're using your own association from `Organisation` to `User`, you can't ever have been using the ones defined in `acts_as_authorization_object` and IIRC, nothing else uses them, so you should be able to replace that call with `include Acl9::ModelExtensions::ForObject` and you should be fine.

I'll close this for now, but if that doesn't work then feel free to reopen.

**Comment by ecoologic** [comment]
Pretty clear, I don't think we've ever used that `acts_as_authorization_object` functionality, all our Roles have `authorizable = nil`, so I am deleting that line of code.  The rest of the update seems to be fine.

Glad to see the project is actively maintained.
Thank you very much for your time and this beautiful gem.
