### ISSUE TITLE
Acl9::AccessDenied after Redis restart with session store set to cache_store

### ISSUE THREAD

**Issue by tenpaiyomi** [be9/acl9#111]
So, prefacing this with the statement that I'm *not sure* that this is an acl9 issue, but I'm starting at the top of the stack and working my way down.

Ruby version **2.5.1**
Rails version **5.2.1**
Acl9 version **3.1.0**

My initial take on this seems to be that, with the initial page load, it recreates the connection to Redis for the session store.  In a page where acl9 does not come into play, the page loads fine and everything goes on its merry way, including the next page load with acl9 requirements.  However, if Redis is restarted and the next page load is one that acl9 is applicable, the page immediately will error out with `Acl9::AccessDenied` on `lib/acl9/controller_extensions/generators.rb:79`.  Subsequent page loads work fine.

The value of code that is being `eval`'d on `generators.rb:77` before the `rescue/raise` is:

```
lambda do |controller|
  unless ((!controller.send(:current_user).nil? && controller.send(:current_user).has_role?('user')) || ((!controller.send(:current_user).nil? && controller.send(:current_user).has_role?('admin')) && Set.new(['suspend','unsuspend','destroy','purge']).include?(controller.action_name)) || ((true) && Set.new(['new','create','forgotten_password','send_password_email','reset_password','perform_reset_password','activation_confirmation','activate','activate_accenture','resend_activation_email']).include?(controller.action_name))) && (true)
    raise Acl9::AccessDenied
  end
end
```

**Comment by smathy** [comment]
I'd say it's the `!controller.send(:current_user).nil?` part of that, ie. `current_user` is returning `nil`.

The `access_control` block just does a call to `before_action`, and those are just run in order, is it possible that your before_action that checks your authentication is **after** your `access_control` block?

**Comment by smathy** [comment]
Closing this because I'm fairly sure it's not an acl9 bug, feel free to reopen with more detail if you find otherwise.

**Comment by smathy** [comment]
Wow, ok :)  Thanks for digging into that, definitely a bizarre one.
