### ISSUE TITLE
Rails 6.0

### ISSUE THREAD

**Issue by juice** [be9/acl9#112]
Hello

i tried to use 6.0.0.rc1 in my Project in combination with acl9 and i get the following message when i start my Rails Server an try to access a page with a access_control block.

`undefined method before_filter for DashboardController:Class
Did you mean?  before_action`

Any plans here to get ACL9 ready for the release of Rails 6.0?

**Comment by smathy** [comment]
Sorry for the delay on this - yes, we'll support 6.  I tend to either do it once it has been released, or in response to a request like this.  Let me take a look later this week.

**Comment by martijncasteel** [comment]
rails 6 is there!

**Comment by kinoflimmern** [comment]
> Sorry for the delay on this - yes, we'll support 6

... last commit 3 years ago? maybe close that stuff?

**Comment by smathy** [comment]
I hadn't really looked at this error.  That issue was fixed in the 3.x versions for Rails 5 (that's when `before_filter` became `before_action`).  Suspect this was just a project that was updated from Rails 4 but acl9 was not upgraded to 3.x.
