### ISSUE TITLE
Check for pre-existing associations?

### ISSUE THREAD

**Issue by zef** [be9/acl9#17]
Roles are great, but it would be awesome to be able to control authorization based on associations that already exist, without having to manually assign a role to a user. For example, let's say a User created a Post, so `@post.creator` returns the user that created it. I want to be able to do this:

    allow :creator, :of => :post

without calling `user.has_role!('creator', post)`.

I know that you can override `#has_role?`, I currently do that to achieve this. I just thought that this could be a rather common issue. My implementation also allows for the same role to be applied to other subjects (users, in this case), so it doesn't get in the way of anything else you would do.

What do you think? Here is my version of `has_role?`

    def has_role?(role_name, object = nil)
      !! if object.nil?
        self.roles.find_by_name(role_name.to_s) ||
        self.roles.member?(get_role(role_name, nil))
      else
        role = get_role(role_name, object)
        subject_owns_object = object.send(role_name) == self if object.respond_to?(role_name)
        (role && self.roles.exists?(role.id)) || subject_owns_object
      end
    end

**Comment by smathy** [comment]
You know, as I try to think of use cases for the documentation I am liking this feature less and less. Every scenario I can think up is solved better with a custom `has_role?` method, keeping the business logic in the user model, rather than in the controller.

**Comment by smathy** [comment]
I've rolled this fix back out, the code is there if anyone really wants it.
