### ISSUE TITLE
Complex roles

### ISSUE THREAD

**Issue by be9** [be9/acl9#3]
Something like

    access_control do
      allow all, :except => :destroy
      allow complex_role, :to => :destroy do
        is :strong
        is :decisive
        is :owner, :of => :object
        is_not :banned
        is_not :fake
      end
    end

**Comment by smathy** [comment]
As I mentioned in #17, I cannot think of a real use case for this that isn't better implemented as a custom `has_role?` method. If you can think of one, then please reopen.
