### ISSUE TITLE
SystemStackError when attempting to add new role to subject

### ISSUE THREAD

**Issue by psulightning** [be9/acl9#87]
```
class User < ActiveRecord::Base
    acts_as_authorized_subject
end

class Role < ActiveRecord::Base
    acts_as_authorized_role
end
```

Using Ruby 1.9.3/Rails 3.2 with acl9 0.12.1, any time I try to `user.role_objects` in my tests I receive a SystemStackError because `Acl9::ModelExtensions::ForSubject#role_objects` will cycle on itself since the default association name is :role_objects.  I know I can pass in the association name, but when I do, `user.destroy` gives a NoMethodError: undefined method `association_class' for nil:NilClass.

Do I have a configuration wrong?  Thanks.

**Comment by psulightning** [comment]
Sorry @smathy, didn't have time to come back and look at this.  Without any parameters sent to `acts_as_authorization_subject`, everything works again.  Thank you.

**Comment by smathy** [comment]
No need to apologize, I appreciate you confirming that it works now. Thanks :smile:
