### ISSUE TITLE
NoMethodError for `access_control` when used in rails-api

### ISSUE THREAD

**Issue by smathy** [be9/acl9#91]
`rails-api` doesn't have `ActionController::Base` which is what the controller methods are attached to.

**Comment by brancusi** [comment]
Currently the work around is to add the acl9 helper to the app controller:

```
class ApplicationController < ActionController::API
  include Acl9::ControllerExtensions
end
```

Looking forward to an update.

Thanks!

**Comment by smathy** [comment]
Thanks for bumping this, and the workaround, I'll have something very shortly.

**Comment by smathy** [comment]
1.2.1 is now out on rubygems

**Comment by brancusi** [comment]
Nice! Thank you!

**Comment by smathy** [comment]
You're welcome. Thanks again for the bump on this, I had the fix sitting locally and had just forgotten to push it up.
