### ISSUE TITLE
Incorrect docs?

### ISSUE THREAD

**Issue by tjchambers** [be9/acl9#94]
In the wiki Role Subsystem I find the following:

Or... since Acl9 defaults can be changed in a special hash, you can put the following snippet:

```
Acl9.config.merge!(
  :default_role_class_name => 'AccountRole',
  :default_subject_class_name => 'Account',
)
```

However in practice and based on what I see in the code this does not work. This *used to* be the way to do this in v1. But it does not work now.

Am I missing something?

**Comment by smathy** [comment]
Thanks Tim, it was an oversight in updating the wiki, which has been fixed now. But also, I never meant to kill that syntax - so I added that back in in 2.1.1. Thanks.
