### ISSUE TITLE
Inadvertent auth success

### ISSUE THREAD

**Issue by smathy** [be9/acl9#99]
``` ruby
  @foo = Foo.find_by id: 'non-existent'

  current_user.has_role? :manager, @foo
```

Currently this will erroneously return `true` for a user with the global `:manager` role, whereas we want it to return false unless that user is specifically a manager of that `@foo`

This is a simple fix for replacing the default for `object` to something (rather than `nil` as it is now), but this will break all existing global roles.

**Comment by smathy** [comment]
Ooh, a worse consequence of this is in the setter!

```ruby
current_user.has_role! :manager, @foo

current_user.has_role? :manager  # => true
```

Yes, sure, you shouldn't be so careless with your code, passing unchecked `nil`s around like they're candy, but still, we can be more careful on inputs.

**Comment by swrobel** [comment]
I don't see a 3.0.0 tag. It's unclear to me whether it includes this fix.

**Comment by smathy** [comment]
Sorry, no.  I re-pushed b47255e which included both this fix and the bump to 3.1.0

**Comment by smathy** [comment]
I just pushed up the version tags, sorry about that.

**Comment by swrobel** [comment]
no worries, thank you for your hard work!!!
